# Generated by Django 2.2.13 on 2022-11-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0004_auto_20221123_1550'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cConoce',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='email',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='cliente',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
