# Generated by Django 2.2.13 on 2022-11-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0005_auto_20221123_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cConoce',
            field=models.CharField(blank=True, choices=[('Publicidad', 'Publicidad'), ('Internet', 'Internet'), ('Amistad', 'Amistad'), ('Agencia', 'Agencia'), ('Otro', 'Otro')], default='Natural', max_length=100, null=True),
        ),
    ]
