# Generated by Django 2.2.13 on 2023-03-03 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0006_auto_20221123_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='facturaenc',
            name='direccion',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='ruc',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='facturaenc',
            name='telefono',
            field=models.FloatField(default=0),
        ),
    ]
