# Generated by Django 2.2.13 on 2023-03-03 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fac', '0007_auto_20230302_2127'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facturaenc',
            old_name='direccion',
            new_name='rucCi',
        ),
        migrations.RemoveField(
            model_name='facturaenc',
            name='ruc',
        ),
        migrations.RemoveField(
            model_name='facturaenc',
            name='telefono',
        ),
    ]
